name: Deploy web app to production

concurrency: production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    if: "!github.event.release.prerelease"

    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: pocolifo/noter-app
          ssh-key: ${{ secrets.APP_GETNOTER_COM_SSH_PRIVATE_KEY }}
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      
      - name: Install dependencies
        working-directory: ./web
        run: npm i

      - name: Build
        working-directory: ./web
        run: npm run build

      - name: Deploy static site to server
        working-directory: ./web
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.APP_GETNOTER_COM_SSH_PRIVATE_KEY }}'
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_ADDRESS 'cd html && rm -rf *'
          scp -r -o StrictHostKeyChecking=no dist/** $SSH_USER@$SSH_ADDRESS:/home/$SSH_USER/html
        env:
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_ADDRESS: ${{ vars.SSH_ADDRESS }}